"""Daily ingestion summary — generate once, persist to disk, reuse everywhere.

The summary is generated by the pipeline (CLI / scheduler) after ingestion
completes. The dashboard reads the saved file and never calls the LLM directly
for summary purposes.

File path: <data_dir>/daily_summary_YYYY-MM-DD.json
"""

from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from moppu.logging_setup import get_logger

log = get_logger(__name__)

KST = timezone(timedelta(hours=9))


def _path(data_dir: Path, date_str: str) -> Path:
    return data_dir / f"daily_summary_{date_str}.json"


def load(data_dir: Path, date_str: str | None = None) -> dict[str, Any] | None:
    """Return the saved summary for *date_str* (default: today KST), or None."""
    ds = date_str or datetime.now(KST).strftime("%Y-%m-%d")
    p = _path(data_dir, ds)
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception as e:
        log.warning("daily_summary.load_failed", path=str(p), err=str(e))
        return None


def generate_and_save(
    session_factory,
    llm,
    data_dir: Path,
    *,
    force: bool = False,
    update_persona: bool = True,
    date_str: str | None = None,
) -> dict[str, Any] | None:
    """Generate LLM summary of ingested videos for a given date and write to disk.

    - ``date_str``: 대상 날짜 (KST, "YYYY-MM-DD"). None이면 오늘.
    - Returns the result dict on success, or None when nothing was ingested.
    - Skips generation (returns cached) if the file already exists, unless ``force=True``.
    """
    from sqlalchemy import desc
    from sqlalchemy.orm import Session

    from moppu.llm.base import ChatMessage
    from moppu.storage.db import Transcript, Video

    target_str = date_str or datetime.now(KST).strftime("%Y-%m-%d")
    save_path = _path(data_dir, target_str)

    if save_path.exists() and not force:
        log.info("daily_summary.cached", date=target_str)
        return json.loads(save_path.read_text(encoding="utf-8"))

    target_date = datetime.strptime(target_str, "%Y-%m-%d").replace(tzinfo=KST)
    midnight_utc = target_date.astimezone(timezone.utc).replace(tzinfo=None)
    next_midnight_utc = (target_date + timedelta(days=1)).astimezone(timezone.utc).replace(tzinfo=None)

    with session_factory() as s:  # type: Session
        transcripts = (
            s.query(Transcript)
            .join(Video, Video.id == Transcript.video_fk)
            .filter(
                Video.created_at >= midnight_utc,
                Video.created_at < next_midnight_utc,
                Video.status == "embedded",
            )
            .order_by(desc(Video.created_at))
            .limit(5)
            .all()
        )
        if not transcripts:
            log.info("daily_summary.no_videos", date=target_str)
            return None

        video_infos: list[dict[str, Any]] = []
        text_parts: list[str] = []
        for tr in transcripts:
            v = s.query(Video).filter_by(id=tr.video_fk).one()
            video_infos.append({
                "video_id": v.video_id,
                "title": v.title,
                "url": v.url or f"https://www.youtube.com/watch?v={v.video_id}",
                "published_at": v.published_at.isoformat() if v.published_at else None,
            })
            text_parts.append(f"[{v.title or v.video_id}]\n{tr.text[:3000]}")

    combined = "\n\n---\n\n".join(text_parts)
    resp = llm.chat(
        messages=[ChatMessage(
            role="user",
            content=(
                "다음은 오늘 수집된 YouTube 영상의 자막입니다. "
                "각 영상의 핵심 주장과 시장 전망을 간결하게 요약해주세요.\n\n"
                f"{combined}"
            ),
        )],
        system="당신은 금융 애널리스트입니다. 한국어로 핵심만 요약하세요.",
    )

    # 요약 기반 추천 질문 3개 생성
    q_resp = llm.chat(
        messages=[ChatMessage(
            role="user",
            content=(
                "다음 요약을 보고, 개인 주식 투자자가 애널리스트에게 할 만한 "
                "구체적인 질문 3가지를 생성해주세요. 각 질문을 한 줄씩, 번호 없이 출력하세요.\n\n"
                + resp.text[:800]
            ),
        )],
        system="주식 투자자 관점의 구체적이고 실용적인 질문 3개만 출력하세요.",
        max_tokens=200,
    )
    raw_lines = [l.strip().lstrip("0123456789.-) ") for l in q_resp.text.strip().split("\n") if l.strip()]
    questions = [q for q in raw_lines if len(q) > 5][:3]

    total_usage = {
        "input_tokens": resp.usage.get("input_tokens", 0) + q_resp.usage.get("input_tokens", 0),
        "output_tokens": resp.usage.get("output_tokens", 0) + q_resp.usage.get("output_tokens", 0),
    }

    result: dict[str, Any] = {
        "date": target_str,
        "summary": resp.text,
        "videos": video_infos,
        "questions": questions,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "usage": total_usage,
    }
    data_dir.mkdir(parents=True, exist_ok=True)
    save_path.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    log.info("daily_summary.saved", date=target_str, path=str(save_path))

    # 페르소나 점진적 업데이트 (오늘 수집 영상 기반 — collect/done 경로와 중복 방지)
    if update_persona:
        new_video_ids = [v["video_id"] for v in video_infos]
        try:
            from moppu.agent.persona import update_with_new
            update_with_new(session_factory, llm, data_dir, new_video_ids)
        except Exception as e:
            log.warning("persona.update_failed", err=str(e))

    return result
